### ISSUE TITLE
Timeout is way too long

### ISSUE THREAD

**Issue by maxcodes** [tamber/tamber-ruby#1]
We're rescuing Exceptions whenever Tamber fails to deliver a response, but the timeout here:
```
lib/tamber.rb:43
  @open_timeout = 30
  @read_timeout = 80
```
is waaay too high. We're waiting more than an entire minute before aborting. I don't think this is expected behavior. 

Mind changing it?

Thanks

**Comment by alexi** [comment]
I agree, those are quite a bit higher than intended usage would expect. We will look into selecting better defaults and will also improve the error handling for timeouts.

For a quick fix, open and read timeouts are configurable:

`Tamber.open_timeout = 1
Tamber.read_timeout = 5
`

**Comment by maxcodes** [comment]
That makes sense. Thanks for that! I hope you're doing well, had some bumps today 🙂
