### ISSUE TITLE
rest-client conflict with other gems (mailjet).

### ISSUE THREAD

**Issue by zyqxd** [tamber/tamber-ruby#4]
Tamber dependencies for `rest-client` is 1 major version behind (currently v2.1). This is causing some conflicts with our codebase which is using mailjet

```
tamber (0.1.14)
      activesupport (>= 4.2.4)
      json (>= 1.8.1)
      rest-client (~> 1.4)
```

Any chance this can be updated?

**Comment by alexi** [comment]
Hi David - We are preparing an update to our API and all SDKs that will be out on Monday, 6/15 that already includes this major version upgrade.

**Comment by zyqxd** [comment]
Great! Thank you

**Comment by alexi** [comment]
Version 0.2.0 is live :) 

Did it fix your issue?

**Comment by zyqxd** [comment]
Hey Alexi,

I've updated a gem, its now throwing an error; here's the stacktrace

/Users/dz/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/app_loader.rb:53:
warning: Insecure world writable dir /Users/dz/.rbenv/versions in PATH,
mode 040777
Traceback (most recent call last):
bin/rails: Bootsnap::LoadPathCache::FallbackScan
...
21: from /Users/dz/Workspace/tamber-test/config/application.rb:7:in `<main>'
...
9: from
/Users/dz/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/tamber-0.2.0/lib/tamber.rb:16:in
`<main>'
...
1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block
in require_with_bootsnap_lfi'
/Users/dz/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in
`require': cannot load such file -- tamber/api_operations/save (LoadError)

This was an attempt on a fresh rails project. I took a look at your source
but it seems like `api_operations/save` is properly defined.

Lmk if you need anything or this is something on my side


*David Zhang*
BASc Computer Engineering
University of Toronto
